version: 0.0
os: linux
files:
  - source: /
    destination: /home/forge/app
permissions:
  - object: /home/forge/app
    owner: forge
    group: www-data
    mode: 775
    type:
      - file

  - object: /home/forge/app
    owner: forge
    group: www-data
    mode: 755
    type:
      - directory

hooks:
#  ApplicationStop:
#    - location: deployment/scripts/application_stop.sh
#      timeout: 300
#      runas: forge
#  BeforeInstall:
#    - location: deployment/scripts/before_install.sh
#      timeout: 300
#      runas: forge
#  DownloadBundle:
#    - location: deployment/scripts/download_bundle.sh
#      timeout: 1200
#      runas: forge
  AfterInstall:
    - location: deployment/scripts/after_install.sh
      timeout: 300
      runas: forge
#  ApplicationStart:
#    - location: deployment/scripts/application_start.sh
#      timeout: 300
#      runas: forge
#  ValidateService:
#    - location: deployment/scripts/validate_service.sh
#      timeout: 300
#      runas: forge
